[package]
name = "dokanifuse"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
byteorder = "1.5.0"
num-derive = "0.4.2"
num-traits = "0.2.19"
plist = "1.8.0"
serde = { version = "1.0", features = ["derive"] }
